---
# OS Patching and Security Updates for Factory Floor Workstations
- name: Update package cache (Ubuntu/Debian)
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  retries: 3
  delay: 10

- name: Update package cache (RHEL/CentOS)
  yum:
    update_cache: true
  when: ansible_os_family == "RedHat"
  retries: 3
  delay: 10

- name: Install security updates only (Ubuntu/Debian)
  apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  when: ansible_os_family == "Debian"
  register: apt_result
  notify: reboot if required

- name: Install security updates (RHEL/CentOS)
  yum:
    name: "*"
    state: latest
    security: true
  when: ansible_os_family == "RedHat"
  register: yum_result
  notify: reboot if required

- name: Install essential packages for factory environment
  package:
    name:
      - curl
      - wget
      - unzip
      - tar
      - chrony  # Time synchronization critical for manufacturing
      - fail2ban  # Security for SSH access
      - ufw  # Firewall management
    state: present

- name: Configure time synchronization for factory operations
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    backup: true
  notify: restart chrony

- name: Enable and start chronyd
  systemd:
    name: chronyd
    enabled: true
    state: started

- name: Configure firewall for Kubernetes
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"      # SSH
    - "6443"    # Kubernetes API
    - "10250"   # Kubelet API
    - "2379"    # etcd client
    - "2380"    # etcd peer
    - "30000:32767"  # NodePort range
  when: node_role is defined

- name: Disable swap for Kubernetes
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    state: absent

- name: Check if reboot is required (Ubuntu/Debian)
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_os_family == "Debian"

- name: Check if reboot is required (RHEL/CentOS)
  shell: needs-restarting -r
  register: reboot_required_rhel
  failed_when: false
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Schedule maintenance window reboot
  reboot:
    reboot_timeout: 600
    test_command: uptime
  when: 
    - (ansible_os_family == "Debian" and reboot_required_file.stat.exists) or
      (ansible_os_family == "RedHat" and reboot_required_rhel.rc == 1)
    - maintenance_window | default(false) | bool
